const fs = require('fs');
const assert = require('assert');
const source = fs.readFileSync('app-classic.js', 'utf8');
const speakStart = source.indexOf('function speakEnglish(text, _rate = 0.82, scope = globalThis)');
const speakEnd = source.indexOf('\n}\n\nconst STORAGE_KEY', speakStart);
assert(speakStart >= 0, 'Voice A speakEnglish function must exist');
assert(speakEnd > speakStart, 'Voice A speakEnglish function must have a bounded body');
const body = source.slice(speakStart, speakEnd);
assert(body.includes('return speakNativeForDirectHtml(text, 0.82, scope);'), 'Voice A must use native speech immediately at the fixed rate');
assert(!body.includes('createEspeakSpeaker({ scope })'), 'Voice A must not depend on eSpeak');
console.log('Voice A native speech test passed');
