const fs = require('fs');
const app = fs.readFileSync('app-classic.js', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const assert = (x, m) => { if (!x) throw new Error(m); };
assert(app.includes('function speakEnglish'), 'classic app must provide speech adapter');
assert(app.includes('speakEnglish(q.answer, state.settings.voiceRate);'), 'practice answer speech must use the speech adapter');
assert(app.includes('createEspeakSpeaker'), 'hosted app must use eSpeak-NG as the primary speech engine');
assert(html.includes('./lib/espeak/espeakng.min.js'), 'eSpeak wrapper must be loaded locally');
assert(html.includes('./app-classic.js'), 'direct HTML app bundle must be loaded');
console.log('speech-practice.test.cjs: PASS');
assert(app.includes('class="order-answer"'), 'practice bundle must include sentence ordering');
assert(app.includes('function bindOrderPractice'), 'practice bundle must include drag ordering behavior');
assert(app.includes("q.type==='sentence-fill'"), 'practice bundle must include fill-in practice');
assert(!app.includes('看看每个单词'), 'old word explanation section must be removed from practice');
console.log('practice-redesign.test.cjs: PASS');
